# Generated by Django 5.2 on 2026-01-18 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_person_hidden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='hidden',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buyer', to='invoices.person'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='seller', to='invoices.person'),
        ),
    ]
